### ISSUE TITLE
Deserialization error in MVC project

### ISSUE THREAD

**Issue by Andmon** [dbolin/Apex.Serialization#81] opened 2020-06-05 06:53 UTC
Hi,
we have a project in MVC environment.
We use Apex.Serialization to serialize and then store byte[] in our DB.
Everything works fine until we stop and restart the IIS Application Pool.
After that (but not every time....) the deserialization of an object saved before result in a 
"Index out of range. Non-negative value and less than the collection size required" exception.
New serialized object works fine (until the next restart).
Subsequent restarts of Application Pool lead to random results (like the object can be deserialized again or every deserialization throw the exception).
The same code, run under windows project, works fine every time.
Thanks
Andrea

**Comment by dbolin** [comment] 2020-06-05 20:57
Could I get a few more details from you?

- What .Net runtime are you using (e.g. 4.7 framework, 3.0 .Net core)
- Do you have a minimal reproduction case?  If not, is the definition of the object which is having problems small enough to post here?
- What version of Apex.Serialization are you referencing?

Based on the description, it sounds like this could be related to some information that is only meaningful at runtime getting serialized (e.g. string hashcodes produced by the default implementation) - although I wouldn't expect this error in that case.  In any case I will need more information to help me reproduce this in order to fix it.

**Comment by Andmon** [comment] 2020-06-08 07:52
Hello,
we're on 4.7.2 framework and 1.3.3 Apex.Serialization.
The serialized objects is the different pages ViewModel, with a lot of nested object, dictionary, list and also interface.
We haven't a minimal case but, in our today tests, seems that create a new instance of the serializer at any call didn't break the code anymore.
In the previous version the serializer was at class level marked as ThreadStatic.
We keep on doing test on it and I'll let you know the results (the error it's randomic, so we aren't sure if we managed to get rid of it).
Thanks a lot
Andrea

**Comment by dbolin** [comment] 2020-06-08 15:27
Well, let me know if you find anything - that exception could definitely happen if the same serializer instance is used by more than one thread, although I wouldn't expect that to happen if it is ThreadStatic and not shared otherwise.

I do want to point out that string-keyed Dictionaries are unlikely to be deserialized correctly unless you specify a StringComparer that produces consistent hashcodes - the default one can produce randomized hashcodes, so they may not match between application runs.  The README has more information on known limitations.  In addition, since Apex.Serialization is schemaless and any change to the application code could make the serialized data unable to be deserialized, I'm not sure I'd recommend this library for your case, unless the data you're serializing to the DB is essentially transient and you're just storing it there to allow multiple servers access to it.

**Comment by dbolin** [comment] 2020-08-14 00:35
Hi Andrea,

Has this been an issue since Jun. 8?  If not I'll close this issue as I have plans to add optional detection of concurrent use.  It's not trivial to do without adding overhead even when it's not enabled though, so it will be a while.

**Closed** 2020-08-21 02:43 UTC
